<?php
/**
 * Plugin Name: VibeStatic
 * Plugin URI:  https://github.com/lignazio/vibestatic
 * Description: Static site generation for WordPress, with incremental deployment.
 * Version:     8.1.0-dev
 * Requires at least: 6.5
 * Requires PHP: 8.2
 * Author:      Ignazio Lucenti
 * Author URI:  https://lucenti.studio
 * License:     GPL-2.0-or-later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: vibestatic
 * Domain Path: /languages
 * Update URI:  https://github.com/lignazio/vibestatic
 *
 * The version picks up where WP2Static stopped — 7.2 — rather than starting at
 * 1.0.0: the code has seven years of history behind it, and pretending
 * otherwise would help nobody understand what they are installing. `-dev` until
 * there is a release.
 *
 * `Requires at least: 6.5` is not caution: the queries use `$wpdb->prepare()`'s
 * `%i` placeholder, which exists from WordPress 6.2, and the i18n sniffs are
 * configured for 6.5. `Update URI` tells WordPress not to look for updates on
 * wordpress.org for a slug that is not ours over there.
 *
 * VibeStatic is a fork of WP2Static, created by Leon Stafford and later
 * maintained by Strattic by Elementor until 2024. The original is released into
 * the public domain (Unlicense); this fork ships under GPLv2 or later.
 *
 * The new name applies to what people read and to what sits on disk. It applies
 * to nothing an add-on can call: the PHP namespace stays `WP2Static\`, the
 * thirty hooks stay `wp2static_*`, the eight tables stay `wp_wp2static_*`, and
 * the admin page slugs stay as they are — they are URLs, and they are the
 * parent add-ons hang their own pages under. Twenty-one existing add-ons keep
 * working untouched, and that is the promise this fork rests on.
 *
 * @package     WP2Static
 */

if ( ! defined( 'ABSPATH' ) ) {
    die;
}

define( 'VIBESTATIC_VERSION', '8.1.0-dev' );
define( 'VIBESTATIC_PATH', plugin_dir_path( __FILE__ ) );

/*
 * The two old names stay defined. None of the twenty-one add-ons uses them —
 * that was checked — but they are published constants, and keeping them alive
 * costs two lines.
 */
define( 'WP2STATIC_VERSION', VIBESTATIC_VERSION );
define( 'WP2STATIC_PATH', VIBESTATIC_PATH );

/*
 * Two autoloaders, not one. `vendor/` holds the plugin's PSR-4 map — WP2Static\
 * onto src/ — while third-party dependencies live in `vendor-prefixed/`, under
 * the WP2Static\Vendor\ namespace, generated by Strauss at build time.
 *
 * The prefix is not cosmetic: WordPress loads every plugin in the same process,
 * and two plugins shipping different versions of Guzzle destroy each other —
 * the first one loaded wins and the other receives a class that is not the one
 * it expects. It is the same problem the leonstafford/wp2staticguzzle fork
 * solved by renaming files by hand, with the difference that here the renaming
 * is automatic and the source is upstream Guzzle, updatable and carrying its
 * security patches.
 */
foreach ( [ 'vendor/autoload.php', 'vendor-prefixed/autoload.php' ] as $vibestatic_autoloader ) {
    if ( ! file_exists( VIBESTATIC_PATH . $vibestatic_autoloader ) ) {
        continue;
    }

    require_once VIBESTATIC_PATH . $vibestatic_autoloader;
}

unset( $vibestatic_autoloader );

if ( ! class_exists( 'WP2Static\Controller' ) ) {
    if ( file_exists( VIBESTATIC_PATH . 'src/WP2StaticException.php' ) ) {
        require_once VIBESTATIC_PATH . 'src/WP2StaticException.php';

        throw new WP2Static\WP2StaticException(
            'VibeStatic cannot find its dependencies: it looks like it was' .
            ' installed from source without being built. Run `composer install`' .
            ' in the plugin directory, or install the zip from a release.'
        );
    }
}

WP2Static\Controller::init( __FILE__ );

/**
 * Define Settings link for plugin
 *
 * The name used to be `plugin_action_links`, in the global namespace: the most
 * generic name possible for a function every WordPress plugin has reason to
 * want to define. Two plugins doing it together would give a redeclaration
 * fatal error, and not to whoever wrote the second one.
 *
 * @param string[] $links array of links
 * @return string[] modified array of links
 */
function vibestatic_plugin_action_links( $links ) {
    $settings_link =
        '<a href="admin.php?page=wp2static">' .
        __( 'Settings', 'vibestatic' ) .
        '</a>';
    array_unshift( $links, $settings_link );

    return $links;
}

add_filter(
    'plugin_action_links_' .
    plugin_basename( __FILE__ ),
    'vibestatic_plugin_action_links'
);

/**
 * Load the plugin's translations.
 *
 * This is genuinely needed, not ceremonial: WordPress's textdomain registry
 * looks on its own in `WP_LANG_DIR/plugins` and `WP_LANG_DIR/themes` — where
 * translations downloaded from wordpress.org land — and nowhere else. The
 * `languages/` directory the plugin ships with enters that list only because
 * `load_plugin_textdomain()` registers it as a custom path; see
 * `WP_Textdomain_Registry::get_paths_for_domain()`.
 *
 * On `init`, and that is where it belongs: since WordPress 6.7, asking for a
 * translation before `after_setup_theme` triggers a `_doing_it_wrong`. The
 * catch is that the check sits behind `$wp_textdomain_registry->has( $domain )`,
 * so it only notices the problem where a translation actually exists: on an
 * English installation nothing happens and the defect stays invisible to
 * whoever is developing, only to surface for whoever runs the plugin
 * translated.
 */
function vibestatic_load_textdomain() : void {
    load_plugin_textdomain(
        'vibestatic',
        false,
        dirname( plugin_basename( __FILE__ ) ) . '/languages'
    );
}

add_action( 'init', 'vibestatic_load_textdomain' );

/**
 * Strip from WordPress's output the things a static site does not need.
 *
 * These were four lines that always ran, with a TODO from the original authors
 * beside them saying they "don't belong in core". The problem is not that they
 * do not belong: it is that a plugin whose job is exporting a site was
 * rewriting that site's output for every visitor, without asking and without
 * saying so.
 *
 * Removing them only during the crawl would have been worse: the static copy
 * would then say something different from what visitors actually receive, and a
 * static copy that does not resemble the original is worth nothing. So either
 * they apply to everyone or to no one — and that is a decision for whoever owns
 * the site, not for the plugin. By default: no one.
 */
function vibestatic_remove_wordpress_cruft() : void {
    if ( ! class_exists( 'WP2Static\CoreOptions' ) ) {
        return;
    }

    if ( ! WP2Static\CoreOptions::getValue( 'removeWordPressCruft' ) ) {
        return;
    }

    /*
     * `wlwmanifest_link` is no longer hooked to wp_head as of WordPress 6.7: the
     * function still exists in deprecated.php but nothing calls it, so this line
     * removes nothing. It stays for sites on older versions.
     */
    remove_action( 'wp_head', 'wlwmanifest_link' );
    remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
    remove_action( 'wp_print_styles', 'print_emoji_styles' );

    add_action(
        'wp_footer',
        function () : void {
            wp_dequeue_script( 'wp-embed' );
            wp_deregister_script( 'wp-embed' );
            wp_dequeue_script( 'comment-reply' );
            wp_deregister_script( 'comment-reply' );
        }
    );
}

/*
 * On `init` rather than immediately: reading the option needs the database, and
 * at this point in WordPress's load $wpdb exists but the plugin's tables may
 * not yet — and in any case the two wp_head callbacks to remove are hooked
 * later.
 */
add_action( 'init', 'vibestatic_remove_wordpress_cruft' );

if ( defined( 'WP_CLI' ) ) {
    WP_CLI::add_command( 'vibestatic', WP2Static\CLI::class );

    /*
     * `wp wp2static` keeps answering. It lives in the deploy scripts and cron
     * entries of everyone who already used the plugin, and breaking it over a
     * rename would be gratuitous damage. It is not deprecated and prints no
     * warnings: it is a second name for the same command.
     */
    WP_CLI::add_command( 'wp2static', WP2Static\CLI::class );
}
