<?php
/**
 * Runs Strauss, which rewrites third-party dependencies from `vendor/` into
 * `vendor-prefixed/` under the WP2Static\Vendor\ namespace.
 *
 * Why go through a script instead of putting `strauss` straight into
 * post-install-cmd: that command also runs during `composer install --no-dev`,
 * where Strauss is a dev dependency that has just been removed. A direct
 * reference to the binary would fail the production install with an error that
 * has nothing to do with the cause.
 *
 * When Strauss is absent, `vendor-prefixed/` is left as it was: exactly the
 * behaviour the build needs, where the directory has already been generated by
 * the full install that precedes it.
 *
 * @package WP2Static
 */

declare( strict_types = 1 );

$binary = __DIR__ . '/../vendor/bin/strauss';

if ( ! file_exists( $binary ) ) {
    fwrite(
        STDERR,
        "Strauss non installato: vendor-prefixed/ lasciata invariata.\n"
    );
    exit( 0 );
}

$command = escapeshellarg( PHP_BINARY ) . ' ' . escapeshellarg( $binary );

passthru( $command, $exit_code );

if ( 0 !== $exit_code ) {
    exit( $exit_code );
}

/*
 * Strauss also generates `vendor/composer/autoload_aliases.php`: 1891 lines
 * registering an autoloader which, on a request for `GuzzleHttp\Client`,
 * aliases it onto the prefixed copy. It exists to keep development code that
 * still uses the original names working, and in Strauss 0.29 it cannot be
 * switched off from configuration: it is turned on automatically when
 * delete_vendor_packages is true (StraussConfig::isCreateAliases()).
 *
 * Inside WordPress that file rebuilds exactly the problem prefixing exists to
 * solve, and makes it worse: the plugin would declare the GuzzleHttp\ namespace
 * again, and another plugin loading its own Guzzle after us would receive OUR
 * version. No longer a collision suffered, one caused.
 *
 * The require in vendor/autoload.php sits inside a file_exists(), so deleting
 * the file is enough and no generated code needs touching.
 */
$aliases = __DIR__ . '/../vendor/composer/autoload_aliases.php';

if ( file_exists( $aliases ) ) {
    unlink( $aliases );
    echo "Rimosso autoload_aliases.php: i nomi originali restano non risolvibili, come deve essere.\n";
}
